### ISSUE TITLE
Tutorial about T2I-Adapter in diffuser

### ISSUE THREAD

**Issue by haofanwang** [TencentARC/T2I-Adapter#10]
[A simple tutorial](https://github.com/haofanwang/T2I-Adapter-for-Diffusers) about loading adapter weights into diffusers framework. As diffusers is one of the most popular framework, you may consider add this tutorial in README.md for potential users.

**Comment by XavierXiao** [comment]
The adaptors are trained on sd v1.4, and you mentioned that they also work on SD v1.5?

**Comment by haofanwang** [comment]
Actually, it should work fine with most of sd-based models, as those models usually finetune on sd1.4/1.5. Back to your question, v1.4 and v1.5 are almost the same where v1.5 trains with more steps.

**Comment by MC-E** [comment]
Thanks! We will add it to our README.

**Comment by MC-E** [comment]
@haofanwang Hi, we have slightly refactored the code. I wonder if it will affect the use of diffuser？

**Comment by haofanwang** [comment]
Let me test it whether the tutorial should also have an update. @MC-E

**Comment by MC-E** [comment]
Thanks for this contribution! We have added it to our acknowledgments.
