### ISSUE TITLE
why unet not frozen?

### ISSUE THREAD

**Issue by wikiwen** [TencentARC/T2I-Adapter#109]
Hello, thanks for your brilliant work. When train coadapters，these information will be printed. The trainable params shows 1.1B. Why unet not frozen? When I set `require_grad`  of all params in unet to `false`，a error  appeared: `RuntimeError: One of the differentiated Tensors does not require grad`.

```
  | Name              | Type               | Params
---------------------------------------------------------
0 | model             | DiffusionWrapper   | 859 M 
1 | first_stage_model | AutoencoderKL      | 83.7 M
2 | cond_stage_model  | FrozenCLIPEmbedder | 123 M 
3 | adapters          | ModuleDict         | 232 M 
4 | coadapter_fuser   | CoAdapterFuser     | 27.3 M
---------------------------------------------------------
1.1 B     Trainable params
206 M     Non-trainable params
1.3 B     Total params
5,302.513 Total estimated model params size (MB)
```

**Comment by wikiwen** [comment]
I figured out. The unet is connected with adapters. Gradients cannot be backwarded to adapter if set unet require_grad  to false.

**Comment by MC-E** [comment]
Hi, the gradient of UNet needs to be enabled during the training process because the gradient needs to be backpropagated to train the adapter, but the parameters of UNet will not be updated.

**Comment by wikiwen** [comment]
> Hi, the gradient of UNet needs to be enabled during the training process because the gradient needs to be backpropagated to train the adapter, but the parameters of UNet will not be updated.

I get it. Thanks for your reply~
