### ISSUE TITLE
Without module 'xformers' (maybe) leads to  the poor result, while with module 'xformers' the code ran failed.

### ISSUE THREAD

**Issue by DesarguesC** [TencentARC/T2I-Adapter#28]
I ran the Keypose Adapter with command:
python test_adapter.py --which_cond keypose --cond_path examples/keypose/person_keypose.png --cond_inp_type keypose --prompt "astronaut, best quality, extremely detailed" --sd_ckpt models/v1-5-pruned-emaonly.ckpt --resize_short_edge 128 --cond_tau 1.0 --cond_weight 1.0 --n_samples 2 --adapter_ckpt models/t2iadapter_keypose_sd14v1.pth

At the first, "No module 'xformers'. Proceeding without it" was reported and I gained a pool result (codes ran normally).
However, after installing 'xformers', codes ran failed with Errors:

![image](https://user-images.githubusercontent.com/100270918/223139723-1ac26a20-fe47-4710-bac0-3cc6a265bc4b.png)

I found some abnormal outputs on Terminal:
![image](https://user-images.githubusercontent.com/100270918/223140808-029b2b37-6e90-49eb-aafc-f3305e018477.png)

**Comment by DesarguesC** [comment]
> The reason you are getting poor results is most likely because you have set the resolution of the generated image too low (i.e., 128, compared to the usual 512).
> 
> Regarding xformers, it appears that it has not been installed correctly. According to the log, this could be due to the pre-built version you downloaded being incompatible with your machine environment.

The question has been solved. Thanks for replying.

**Comment by Zhangwenyao1** [comment]
> > 您获得较差结果的原因很可能是因为您将生成的图像的分辨率设置得太低（即 128，而通常为 512）。
> > 关于 xformers，似乎没有正确安装。根据日志，这可能是由于您下载的预构建版本与您的机器环境不兼容。
> 
> 问题已解决。谢谢回复。



> > The reason you are getting poor results is most likely because you have set the resolution of the generated image too low (i.e., 128, compared to the usual 512).
> > Regarding xformers, it appears that it has not been installed correctly. According to the log, this could be due to the pre-built version you downloaded being incompatible with your machine environment.
> 
> The question has been solved. Thanks for replying.

Thansks for your effort!
Can you share the way to solve this issue?
