### ISSUE TITLE
stuff_train2017_pixelmaps or stuffthingmaps_trainval2017 for train_sketch.py? 

### ISSUE THREAD

**Issue by twotwoiscute** [TencentARC/T2I-Adapter#35]
I would like to know which COCO dataset shoud I download to  right data for https://github.com/TencentARC/T2I-Adapter/blob/a6223039a683c277777be0a1ce4edf82f3abb3c3/train_sketch.py#L231
I found two kinds of mask data, one is  `stuff_train2017_pixelmaps` and the other one is `stuffthingmaps_trainval2017` ,`stuff_train2017_pixelmaps` looks more colorful. 
Could you  please tell me which  one should I download? Thanks!

**Comment by MC-E** [comment]
Please refer to the preprocess_mask.py in https://github.com/PITI-Synthesis/PITI/tree/main/preprocess.

**Comment by twotwoiscute** [comment]
Thanks, I found some similiar label in [2017 Stuff Train/Val annotations [1.1GB]](http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip), there is a zip file called something like `pixelmaps.zip` which has similiar apperance to the one generated from [https://github.com/PITI-Synthesis/PITI/tree/main/preprocess.](https://github.com/PITI-Synthesis/PITI/tree/main/preprocess), later one does produce more fine-grained pixel label. 


> Please refer to the preprocess_mask.py in https://github.com/PITI-Synthesis/PITI/tree/main/preprocess.

Thanks, I found some similiar label in [2017 Stuff Train/Val annotations [1.1GB]](http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip), there is a zip file called something like `pixelmaps.zip` which has similiar apperance to the one generated from [https://github.com/PITI-Synthesis/PITI/tree/main/preprocess.](https://github.com/PITI-Synthesis/PITI/tree/main/preprocess), later one does produce more fine-grained pixel label.

**Comment by twotwoiscute** [comment]
> Please refer to the preprocess_mask.py in https://github.com/PITI-Synthesis/PITI/tree/main/preprocess.

Thanks, I found some similiar label in [2017 Stuff Train/Val annotations [1.1GB]](http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip), there is a zip file called something like `pixelmaps.zip` which has similiar apperance to the one generated from [https://github.com/PITI-Synthesis/PITI/tree/main/preprocess.](https://github.com/PITI-Synthesis/PITI/tree/main/preprocess), later one does produce more fine-grained pixel label.

**Comment by dmmSJTU** [comment]
@twotwoiscute hi, If you want to use https://github.com/PITI-Synthesis/PITI/tree/main/preprocess/preprocess_mask.py to colorize the raw mask, how can you obtain the raw mask? Look forward for your reply.
