### ISSUE TITLE
Request: Automatic1111 Extension Version

### ISSUE THREAD

**Issue by Vigilence** [TencentARC/T2I-Adapter#49]
I would love to see this as an extension for automatic1111.  I am aware of https://github.com/Mikubill/sd-webui-controlnet but its very confusing to use, buggy and lacking documentation.

**Comment by MC-E** [comment]
Thanks for your attention. We are working on it.

**Comment by Vigilence** [comment]
> Thanks for your attention. We are working on it.

Wow that's awesome!
