### ISSUE TITLE
About CLIP evaluation

### ISSUE THREAD

**Issue by resindraburiza** [TencentARC/T2I-Adapter#57]
Hi,

First of all, I would like to thank the authors for the great work and for sharing the code with us. I have read both the paper and the code. I am interested about the CLIP evaluation method.

I am aware that in the paper, it is mentioned that the authors used (ViT-L/14) as the CLIP evaluator. Unfortunately, there are no evaluation code/implementation in this github repo. Would you mind to share the evaluation implementation with us?
The reason is that, I have tried to evaluate generative model using two CLIP libraries ,e.g., [Torchmetrics](https://torchmetrics.readthedocs.io/en/stable/multimodal/clip_score.html)  and [open clip](https://github.com/mlfoundations/open_clip). Unfortunately, both give different results, albeit small. So I am just wondering which library did you use to evaluate? Or did you implement the evaluation pipeline all by yourself?

Thank you very much. Really looking forward to hear from you!

Best regards,

**Comment by MC-E** [comment]
Hi, we use the Open CLIP to calculate the CLIP score. You can refer to the example in https://github.com/openai/CLIP#:~:text=import%20torch-,import%20clip,-from%20PIL%20import

Our code:
            image_features = model.encode_image(image)
            text_features = model.encode_text(text)
            image_features = image_features / image_features.norm(dim=1, keepdim=True)
            text_features = text_features / text_features.norm(dim=1, keepdim=True)
            sim = F.cosine_similarity(image_features, text_features)
            sim = sim.cpu().data.numpy().astype(np.float32)

Best,

**Comment by resindraburiza** [comment]
Hi MC-E,

thank you very much for your reply! I really appreciate that you reply to my message despite your bussy time. It sure really helps a lot.
Please let me use it as reference to implement my evaluation pipeline.

Best regards,
