### ISSUE TITLE
Plans for continued development and release?

### ISSUE THREAD

**Issue by createchange** [TencentARC/T2I-Adapter#63]
Newer releases of ControlNet have brought various pre-processors for face control [1]. When using these with the T2I openpose adapter, I get failed results.

The release notes state that the architecture did not change (and they don't plan to change until at least v1.5, if ever) [1], but it doesn't seem that they work well together at this point.

I am mostly curious if this is a dead project. That would be unfortunate, as the time to generate an image is greatly reduced with these adapters, as compared to the "official" ones. 

[1]: https://github.com/lllyasviel/ControlNet-v1-1-nightly

**Comment by MC-E** [comment]
Our future development will focus on CoAdapter https://huggingface.co/spaces/Adapter/CoAdapter. A new update for CoAdapter is coming.
