### ISSUE TITLE
where is " cubic function" for "t"?

### ISSUE THREAD

**Issue by ZihaoW123** [TencentARC/T2I-Adapter#82]
![image](https://github.com/TencentARC/T2I-Adapter/assets/47708655/6500de85-a433-43d8-aa97-603f53a2c758)
In the paper, "t" is sampled from a  cubic function. But I can not find the code in this repo. Where is the implementation for this feature?

**Comment by jiazheng-xing** [comment]
Hi~ Do you know where is the cubic function for t in the code.
