### ISSUE TITLE
T2i adapter SDXL for color and using multiple adapters.

### ISSUE THREAD

**Issue by jquintanilla4** [TencentARC/T2I-Adapter#89]
I was reading your paper. According to your figure 3, you can compound multiple t2i adapters into the U-net denoising process. However in this repo or in the huggingface tutorials, you do not provide any guidance to do so, is that forthcoming?

Also, I noticed that you guys did work on T2i color adapter for SD 1.4, but not yet for SDXL. Are you guys working on that? if not, is there a way for the community to help?

Anyways, thanks for your research and development work. Super interesting approach.

**Comment by MC-E** [comment]
Yeah, we will continue to collaborate with diffusers team in the future, providing more adapter support. 
We also provide the training script, so that the community can conduct more interesting experiments and explorations.

**Comment by jquintanilla4** [comment]
Thanks for the reply. I'll look more into the training script and how to use it to build a SDXL color adapter. Look forward to seeing more on combining multiple t2i adapters.
