### ISSUE TITLE
Training CoAdapter: Couldnt figure out dataloader

### ISSUE THREAD

**Issue by enkaranfiles** [TencentARC/T2I-Adapter#99]
Hello @MC-E,

I am trying to run train.py(SD branch),

For the training part,

I am using this YAML: https://github.com/TencentARC/T2I-Adapter/blob/main/configs/pl_train/coadapter-v1-train.yaml
and as you suggest it, I am trying to use this documentation: https://github.com/TencentARC/T2I-Adapter/blob/main/docs/coadapter.md

For the training, I am using LAION-set. But I think that I couldnt figure out training data format!

I tried to create webdataset format, created json file associated with images. (tar based)

But every time, I stuck in the same position:

```
cli config

  | Name              | Type               | Params
---------------------------------------------------------
0 | model             | DiffusionWrapper   | 859 M 
1 | first_stage_model | AutoencoderKL      | 83.7 M
2 | cond_stage_model  | FrozenCLIPEmbedder | 123 M 
3 | adapters          | ModuleDict         | 288 M 
4 | coadapter_fuser   | CoAdapterFuser     | 27.3 M
5 | clip_vision_model | CLIPVisionModel    | 303 M 
6 | midas_model       | MiDaSInference     | 123 M 
7 | sketch_model      | PiDiNet            | 710 K 
---------------------------------------------------------
1.2 B     Trainable params
633 M     Non-trainable params
1.8 B     Total params
7,236.818 Total estimated model params size (MB)
Loading webdataset with 1 shards.
Loading webdataset with 1 shards.
Loading webdataset with 1 shards.
Loading webdataset with 1 shards.
```

I saw these things and training does not start. No error or No warnings! Should I wait more or can you help me for data preparation part?

**Comment by MC-E** [comment]
Hi @enkaranfiles , is the LAION data you downloaded in this format?
![image](https://github.com/TencentARC/T2I-Adapter/assets/54032224/6bde31ec-40e7-485a-b4ea-2cd668e2cbde)
![image](https://github.com/TencentARC/T2I-Adapter/assets/54032224/82da8e4f-93e3-4a13-baf9-ad5213307812)

**Comment by enkaranfiles** [comment]
thank you @MC-E, I realized that later. 

For everyone here is the link for image2dataset: https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion-aesthetic.md

**Comment by zjysteven** [comment]
@enkaranfiles Hi, may I ask how did you set the argument `shards` here?
https://github.com/TencentARC/T2I-Adapter/blob/16bba674b472121d5a86e3ed6b935f91d516bc74/configs/pl_train/coadapter-v1-train.yaml#L136
I noticed how this argument is used in the script, but still I'm not sure how to set it correctly. Did you just pass a single shard or a list of shards?
https://github.com/TencentARC/T2I-Adapter/blob/16bba674b472121d5a86e3ed6b935f91d516bc74/ldm/data/dataset_laion.py#L82
